In [145]:
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import os, glob

datagen = ImageDataGenerator(rotation_range=36,
                             width_shift_range=0.2,
                             height_shift_range=0.2,
                             shear_range=0.2,
                             zoom_range=0.2,
                             horizontal_flip=True,
                             fill_mode='nearest')
dir_list = os.listdir(path='test')
class_list = []
for file in dir_list:
    if file.endswith("_class"):
        class_list.append(file)
print(class_list)
#for folder in class_list:
#    img_aug(folder_path="test/out/"+folder)
def img_aug(file_ends=[".jpg",".jpeg", ".png", ".PNG"], folder_path="test/", save_format='jpeg', class_path=None, img_count=1):
    dir_list = os.listdir(path=class_path)
    img_list = []
    for file in dir_list:
        for end in file_ends:
            if file.endswith(end):
                img_list.append(file) 
    print(img_list)
    for img in img_list:
        img_t = load_img(class_path + "/" + img)
        #x = img_t.resize((150,150))
        x = img_to_array(img_t)  # this is a Numpy array with shape (3, 150, 150)
        x = x.reshape((1,) + x.shape)  # this is a Numpy array with shape (1, 3, 150, 150)

# the .flow() command below generates batches of randomly transformed images
# and saves the results to the `preview/` directory
        if not os.path.exists(folder_path):
            os.mkdir(os.path.join(folder_path))
        i = 0
        print(img[:-4] + str(i))
        for batch in datagen.flow(x, batch_size=1,
                                  save_to_dir=folder_path, 
                                  save_prefix= img[:-4] , 
                                  save_format=save_format):
            print(i)
            i += 1
            if i > img_count:
                break  # otherwise the generator would loop indefinitely
for folder in class_list:
    img_aug(class_path="test/" + folder,folder_path="test/control/"+ folder + "/", img_count = 50)

['kashkin_class', 'kiril_class', 'kruglova_class', 'misha_class', 'oleg_class']
['kashkin.jpg', 'Kashkin2.png', 'Kashkin3.png', 'kashkin4.jpg']
kashkin0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
Kashkin20
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
Kashkin30
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
kashkin40
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
['Kiril.jpg', 'Kiril2.jpg', 'Kiril3.jpg', 'Kiril4.png']
Kiril0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
Kiril20
0
1
2
3
4
5
6
7
8
9
10
11
12
13

In [15]:
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D, MaxPooling2D
from tensorflow.python.keras.layers import Activation, Dropout, Flatten, Dense
from keras.optimizers import RMSprop, Adam
import numpy as np
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import os, glob

In [16]:
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'test/control',
        target_size=(150, 150),
        batch_size=30,
        class_mode='categorical')

validation_generator = test_datagen.flow_from_directory(
        'test/control',
        target_size=(150, 150),
        batch_size=30,
        class_mode='categorical')



Found 1773 images belonging to 5 classes.
Found 1773 images belonging to 5 classes.


In [25]:
model = Sequential()
model.add(Conv2D(32, (5, 5), input_shape=(150, 150, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))


model.add(Conv2D(64, (4, 4)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Dropout(0.5))

#model.add(Conv2D(128, (4, 4)))
#model.add(Activation('relu'))
#model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Dropout(0.5))

model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Dropout(0.2))

model.add(Flatten())
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation('softmax'))



model.compile(loss='categorical_crossentropy',
              optimizer=optimize,
              metrics=['accuracy'])

# Размер мини-выборки
batch_size = 3
# Количество изображений для обучения
nb_train_samples = 30
# Количество изображений для проверки
nb_validation_samples = 6
# Количество изображений для тестирования
nb_test_samples = 6
model.fit_generator(
        train_generator,
        steps_per_epoch=1773//5,
        epochs=15,
        validation_data=validation_generator,
        validation_steps=8)

scores = model.evaluate_generator(validation_generator, nb_test_samples // batch_size)
print("Аккуратность на тестовых данных: %.2f%%" % (scores[1]*100))


ValueError: ('Could not interpret optimizer identifier:', <keras.optimizers.RMSprop object at 0x000001E82C75C828>)

In [10]:
class_ = [["Kashkin"], ["Kiril"], ["Kruglova"], ["Misha"], ["Oleg"]]
def img_pred(file_end=[".jpeg", ".png", "jpg"], path_pred="test/"):
    
    list_file = os.listdir(path_pred)
    list_img = []
    print(list_file)
    for file in list_file:
        for end in file_end:
            if file.endswith(end):
                list_img.append(file)
    for file in list_img:       
        img = load_img(path_pred + file)  # this is a PIL image
        img = img.resize((150,150))
        x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
        x = x.reshape((1,) + x.shape)  # this is a Numpy array with shape (1, 3, 150, 150)
        x = x/255
        h = model.predict_classes(x) 
        z = model.predict(x)
        #print(str(class_[h[0]]) + " {:.4f} {:.4f} {:.4f}".format(z[0][0], z[0][1], z[0][2]))
        print(file + " " + str(class_[h[0]]) + " {:.2f}%".format(z[0][h[0]]*100))
        print(z)
        #print((z[0][0]))

In [11]:
img_pred()

['control', 'Kashkin.png', 'kashkin4.jpg', 'kashkin_class', 'Kiril4.png', 'Kirill.png', 'kiril_class', 'Kruglova.png', 'Kruglova4.PNG', 'kruglova_class', 'Misha.png', 'Misha4.PNG', 'misha_class', 'Oleg.png', 'Oleg4.png', 'oleg_class']
Kashkin.png ['Oleg'] 43.43%
[[2.0690763e-03 3.1827235e-01 1.9455995e-04 2.4515118e-01 4.3431288e-01]]
kashkin4.jpg ['Kashkin'] 99.20%
[[9.9200153e-01 3.8031200e-03 7.2873634e-04 2.7080318e-05 3.4395487e-03]]
Kiril4.png ['Kiril'] 99.98%
[[1.7531654e-04 9.9980432e-01 9.1993591e-08 2.0192776e-05 9.2702557e-08]]
Kirill.png ['Kiril'] 99.99%
[[1.7424993e-05 9.9994600e-01 5.4644307e-09 3.6350793e-05 2.0649833e-07]]
Kruglova.png ['Misha'] 99.14%
[[5.2949414e-20 4.1266734e-15 8.6057261e-03 9.9138814e-01 6.1866563e-06]]
Misha.png ['Kashkin'] 52.24%
[[0.5223568  0.05832426 0.09095567 0.0615856  0.26677766]]
Oleg.png ['Misha'] 100.00%
[[0.000000e+00 0.000000e+00 5.462705e-16 1.000000e+00 5.822118e-25]]
Oleg4.png ['Oleg'] 99.84%
[[1.6167307e-09 6.5704407e-11 1.8589081